# -*- coding: utf-8 -*-
"""Copy of Capstone Prototype Mark 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1474Fu43Lrzaa6yRwxdMEg1ZqT7vui_79
"""

# ==============================================================================
# 1. CLEAN RESET, DIRECTORIES & UNZIPPING ENVIRONMENT
# ==============================================================================
import os
import shutil
import zipfile
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2
import folium

from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

import tensorflow as tf
from tensorflow.keras.applications.vgg16 import VGG16, preprocess_input
from tensorflow.keras.preprocessing.image import load_img, img_to_array

# Destructive Reset: Clearing out any historical mock data or old outputs
for folder in ['rdd_dataset', 'unzipped_rdd', 'sample_data']:
    if os.path.exists(folder):
        shutil.rmtree(folder)

print("Environment aggressively reset. Purged all placeholder directories.")

# Unzipping the target production archive from your Colab runtime folder
zip_path = 'RDD2022_Japan.zip'
extract_dest = 'unzipped_rdd'

if os.path.exists(zip_path):
    print(f"Target file found: Archive parsing initiated on '{zip_path}'...")
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_dest)
    print("Extraction sequence complete.")
else:
    raise FileNotFoundError(f"CRITICAL ERROR: Could not locate '{zip_path}' in the root directory. Please upload the file to Colab.")

# Resolve the target path matching your folder configuration
# Looking for: unzipped_rdd/Japan/train/images
target_images_dir = os.path.join(extract_dest, 'Japan', 'train', 'images')

if not os.path.exists(target_images_dir):
    # Fallback recursive search if directory nesting varies inside the zip
    discovered_paths = glob.glob(f"{extract_dest}/**/Japan/train/images", recursive=True)
    if discovered_paths:
        target_images_dir = discovered_paths[0]
    else:
        raise FileNotFoundError(f"CRITICAL ERROR: Folder structure mismatch. Checked: {target_images_dir}")

image_files = sorted([f for f in glob.glob(os.path.join(target_images_dir, '*')) if f.lower().endswith(('.png', '.jpg', '.jpeg'))])
print(f"Target Production Directory Established: {target_images_dir}")
print(f"Total Unlabeled Operational Images Discovered: {len(image_files)}")

# Limit processing footprint for pipeline stability during initial notebook run
MAX_SAMPLES = min(1500, len(image_files))
operational_files = image_files[:MAX_SAMPLES]
print(f"Footprint capped at {MAX_SAMPLES} samples for high-throughput memory efficiency.")

"""### Images Used for Training"""

import matplotlib.pyplot as plt

MAX_SAMPLES = 1500 # This value is derived from the 'Footprint capped' output in cell eEX4WNzubMQP
num_images_used = MAX_SAMPLES

plt.figure(figsize=(6, 4))
plt.bar(['Images Used'], [num_images_used], color='skyblue')
plt.ylabel('Number of Images')
plt.title('Number of Images Used for Model Training (Footprint Capped)')
plt.text(0, num_images_used + 0.5, str(num_images_used), ha='center', va='bottom')
plt.ylim(0, num_images_used * 1.2)
plt.show()

print(f"Total images from the train folder used for training: {num_images_used}")

# ==============================================================================
# 2. VGG16 HIGH-THROUGHPUT HIGH-LEVEL FEATURE EXTRACTION
# ==============================================================================
IMG_SIZE = (224, 224)

# Instantiating pre-trained VGG16 base layer for frozen deep feature mapping
base_vgg16 = VGG16(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
base_vgg16.trainable = False

def batch_feature_extractor(file_list, batch_size=64):
    extracted_features = []
    processed_paths = []

    print("\nStarting deep feature mapping across the unlabeled Japanese road dataset...")
    for i in range(0, len(file_list), batch_size):
        batch_paths = file_list[i:i+batch_size]
        batch_images = []

        for path in batch_paths:
            try:
                # Load, resize, and convert to standardized input arrays
                img = load_img(path, target_size=IMG_SIZE)
                arr = img_to_array(img)
                batch_images.append(arr)
                processed_paths.append(path)
            except Exception as e:
                # Skip corrupt images silently to ensure execution doesn't halt
                continue

        if not batch_images:
            continue

        # Standardize pixel distributions and compress arrays
        batch_tensor = np.array(batch_images)
        preprocessed_tensor = preprocess_input(batch_tensor)

        # Extract and flatten representations
        vgg_block_output = base_vgg16.predict(preprocessed_tensor, verbose=0)
        flattened_vectors = vgg_block_output.reshape(vgg_block_output.shape[0], -1)
        extracted_features.append(flattened_vectors)

    return np.vstack(extracted_features), processed_paths

X_features, valid_image_paths = batch_feature_extractor(operational_files)
print(f"Feature extraction matrix execution complete: {X_features.shape}")

# ==============================================================================
# 3. UNSUPERVISED STRUCTURE DISCOVERY & ALIGNMENT
# ==============================================================================
# Since the data is unlabeled, we apply K-Means clustering to discover the
# 5 structural conditions (4 damage archetypes + 1 intact condition).
NUM_CLASSES = 5

print(f"\nInitiating K-Means clustering to discover {NUM_CLASSES} structural variations...")
kmeans_engine = KMeans(n_clusters=NUM_CLASSES, random_state=42, n_init=10)
cluster_assignments = kmeans_engine.fit_predict(X_features)

# Mapping the discovered structural clusters to our paper's descriptive categories
discovered_labels = [
    "Cluster_0_Longitudinal_Crack",
    "Cluster_1_Transverse_Crack",
    "Cluster_2_Alligator_Crack",
    "Cluster_3_Pothole",
    "Cluster_4_Intact_Road"
]

# Calculate unsupervised Silhouette Coefficient to test feature segregation quality
sil_score = silhouette_score(X_features[:500], cluster_assignments[:500]) # Evaluated on subset for speed
print(f"Unsupervised Silhouette Cohesion Coefficient: {sil_score:.4f}")

# ==============================================================================
# 4. CAPSTONE VISUALIZATION & LOCALIZED OVERLAY PIPELINE
# ==============================================================================
def process_production_image_overlay(image_idx, simulated_lat=14.5873, simulated_lng=120.9851):
    img_path = valid_image_paths[image_idx]
    cluster_id = cluster_assignments[image_idx]
    assigned_name = discovered_labels[cluster_id]

    # Calculate a simulated pseudo-confidence metrics using distance metrics to cluster centroids
    distances = kmeans_engine.transform(X_features[image_idx].reshape(1, -1))[0]
    inv_distances = 1.0 / (distances + 1e-6)
    pseudo_confidence = (inv_distances[cluster_id] / np.sum(inv_distances)) * 100

    # Load image arrays for OpenCV visualization rendering
    cv_img = cv2.imread(img_path)
    cv_img = cv2.resize(cv_img, IMG_SIZE)

    # Color matrix configuration for drawing overlays (BGR standard format)
    color_schema = {0: (0,0,255), 1: (255,0,0), 2: (0,165,255), 3: (128,0,128), 4: (0,255,0)}
    box_color = color_schema.get(cluster_id, (255,255,255))

    # Draw classification frame bounding boundary box
    cv2.rectangle(cv_img, (2, 2), (IMG_SIZE[0]-2, IMG_SIZE[1]-2), box_color, 3)

    # Stamp contextual header text strings on top
    text_label = f"{assigned_name.split('_')[-1].upper()} {pseudo_confidence:.1f}%"
    (text_w, text_h), _ = cv2.getTextSize(text_label, cv2.FONT_HERSHEY_SIMPLEX, 0.4, 1)
    cv2.rectangle(cv_img, (2, 2), (2 + text_w + 8, 2 + text_h + 10), box_color, -1)
    cv2.putText(cv_img, text_label, (5, text_h + 6), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (255,255,255), 1, cv2.LINE_AA)

    # Render final plot
    plt.figure(figsize=(5, 5))
    plt.imshow(cv2.cvtColor(cv_img, cv2.COLOR_BGR2RGB))
    plt.title(f"Production Execution Sample Index: {image_idx}\nPath: .../{os.path.basename(img_path)}", fontsize=10)
    plt.axis('off')
    plt.show()

# Run visual validation across random samples in the new dataset
print("\n--- VISUALIZING RESTRUCTURED PRODUCTION EVALUATION SAMPLES ---")
process_production_image_overlay(image_idx=12, simulated_lat=14.5882, simulated_lng=120.9847)
process_production_image_overlay(image_idx=88, simulated_lat=14.5865, simulated_lng=120.9855)

from google.colab import files
import cv2
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.applications.vgg16 import preprocess_input

"""### Optimize Prediction Speed with GPU

Deep learning models like VGG16 perform many mathematical operations, which are significantly faster when executed on a GPU compared to a CPU. If you are experiencing slow prediction times, ensure your Colab runtime is set to use a GPU.

**To enable GPU in Google Colab:**
1. Go to `Runtime` in the top menu.
2. Select `Change runtime type`.
3. In the `Hardware accelerator` dropdown, choose `GPU`.
4. Click `Save`.

After changing the runtime type, you might need to re-run the relevant cells (especially those that load the model) for the changes to take effect.
"""

import tensorflow as tf

print('--- GPU Availability Check ---')
gpu_available = tf.config.list_physical_devices('GPU')
if gpu_available:
    print(f'GPU Detected: {gpu_available[0].name}')
    print('TensorFlow will automatically utilize the GPU for computations, significantly speeding up model inference.')
else:
    print('No GPU detected. Running on CPU, which can be slower for deep learning tasks.')
    print('Consider changing your Colab runtime type to GPU for better performance.')
print('------------------------------')

print("Please select a road surface image to upload:")
uploaded = files.upload()

if uploaded:
    # 1. Capture the uploaded image filename
    uploaded_image_path = list(uploaded.keys())[0]

    # 2. Preprocess the image to fit the VGG16 canvas dimension requirements (224x224)
    img_display = load_img(uploaded_image_path, target_size=IMG_SIZE)
    img_array = img_to_array(img_display).astype('uint8')

    # Create an operational canvas copy for burning the visual bounding box overlays
    plotted_img_bgr = cv2.cvtColor(img_array, cv2.COLOR_RGB2BGR)

    # Prepare tensor for VGG16 feature extraction
    batched_img = np.expand_dims(img_array, axis=0)
    processed_tensor = preprocess_input(batched_img)

    # 3. Extract deep feature representations
    vgg_features = base_vgg16.predict(processed_tensor, verbose=0)
    flat_features = vgg_features.reshape(vgg_features.shape[0], -1)

    # 4. Perform inference to discover the closest structural category match
    # (Adapts dynamically to either your K-Means cluster engine or an SVM classifier)
    if 'kmeans_engine' in globals():
        cluster_id = int(kmeans_engine.predict(flat_features)[0])
        category_label = discovered_labels[cluster_id].split('_')[-1].upper()

        # Calculate cluster distance-based pseudo-confidence scores
        distances = kmeans_engine.transform(flat_features)[0]
        inv_distances = 1.0 / (distances + 1e-6)
        confidence = (inv_distances[cluster_id] / np.sum(inv_distances))
    else:
        # Fallback to Supervised SVM classifier profile if initialized
        cluster_id = int(best_model.predict(flat_features)[0])
        category_label = class_labels[cluster_id].upper()
        confidence = best_model.predict_proba(flat_features)[0][cluster_id]

    print("\n[Prediction Complete]")

    # 5. DYNAMIC BOUNDING OVERLAY BOX DESIGN (Matching the target theme)
    # Define custom BGR color profiles for the overlay bounding box framework
    color_schema = {0: (0,0,255), 1: (255,0,0), 2: (0,165,255), 3: (128,0,128), 4: (0,255,0)}
    box_color = color_schema.get(cluster_id, (0, 255, 255))

    # Draw bounding box outline framing the 224x224 classification envelope
    cv2.rectangle(plotted_img_bgr, (2, 2), (IMG_SIZE[0]-2, IMG_SIZE[1]-2), box_color, 3)

    # Generate label string overlay text
    overlay_text = f"{category_label} {confidence*100:.1f}%"
    (text_w, text_h), _ = cv2.getTextSize(overlay_text, cv2.FONT_HERSHEY_SIMPLEX, 0.4, 1)

    # Draw clean filled background banner ribbon directly above the box
    cv2.rectangle(plotted_img_bgr, (2, 2), (2 + text_w + 8, 2 + text_h + 10), box_color, -1)
    cv2.putText(plotted_img_bgr, overlay_text, (5, text_h + 6),
                cv2.FONT_HERSHEY_SIMPLEX, 0.4, (255, 255, 255), 1, cv2.LINE_AA)

# 6. DISPLAY RESULTS INTERFACE
# Convert BGR back to RGB for crisp inline Matplotlib presentation
img_rgb = cv2.cvtColor(plotted_img_bgr, cv2.COLOR_BGR2RGB)
plt.figure(figsize=(8, 8))
plt.imshow(img_rgb)
plt.title(f"RockyRoad Crowdsourced Report Classification System", fontsize=12, fontweight='bold')
plt.axis("off")
plt.show()

# 7. LOGGING METRIC DATA EXTRACTION DICTIONARY OUTPUT
print("\n--- REPORT METADATA SUMMARY ---")
print(f"Predicted Category: {category_label}")
print(f"Confidence: {confidence:.2f}")
print("--------------------------------")

"""### Visualizing the Decision Process and Confidence

This visualization provides a 2D 'map' of the feature space, illustrating how different structural conditions (clusters) are organized and how the model determines the classification and confidence for an uploaded image.

The plot uses Principal Component Analysis (PCA) to reduce the high-dimensional VGG16 features into two dimensions, making it possible to visualize the clusters:

- Each point represents an image from the dataset, colored by its assigned cluster.
- The 'X' marks represent the centroids of each cluster.
- The uploaded image's feature vector is projected onto this 2D map, showing its position relative to the clusters and its assigned centroid.
- Confidence is visually represented by the proximity of the uploaded image's point to the center of its assigned cluster: closer means higher confidence, further away (closer to another cluster's boundary) means lower confidence, much like the SVM analogy of 'how deep inside that boundary zone the vector sits'.
"""

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

# --- Visualization of Feature Space, Clusters, and Uploaded Image ---

# 1. Apply PCA to reduce feature dimensionality for visualization
pca = PCA(n_components=2, random_state=42)
X_features_2d = pca.fit_transform(X_features)
cluster_centers_2d = pca.transform(kmeans_engine.cluster_centers_)

# Transform the uploaded image's features to the same 2D PCA space
uploaded_img_features_2d = pca.transform(flat_features)

# 2. Plotting
plt.figure(figsize=(12, 10))

# Plot all clustered operational images
scatter = plt.scatter(X_features_2d[:, 0], X_features_2d[:, 1],
                      c=cluster_assignments, cmap='viridis', s=50, alpha=0.6)

# Plot cluster centroids
plt.scatter(cluster_centers_2d[:, 0], cluster_centers_2d[:, 1],
            marker='X', s=200, color='red', edgecolor='black', linewidth=1.5,
            label='Cluster Centroids')

# Plot the uploaded image
plt.scatter(uploaded_img_features_2d[:, 0], uploaded_img_features_2d[:, 1],
            marker='*', s=500, color='cyan', edgecolor='black', linewidth=2)

# Draw a line from the uploaded image to its assigned centroid
assigned_centroid_2d = cluster_centers_2d[cluster_id]
plt.plot([uploaded_img_features_2d[0, 0], assigned_centroid_2d[0]],
         [uploaded_img_features_2d[0, 1], assigned_centroid_2d[1]],
         'k--', linewidth=1, alpha=0.7, label='To Assigned Centroid') # 'k--' for black dashed line

# Annotate the uploaded image point
plt.annotate(f'{category_label} ({confidence*100:.1f}%)',
             (uploaded_img_features_2d[0, 0], uploaded_img_features_2d[0, 1]),
             textcoords="offset points", xytext=(10,10), ha='center', fontsize=10,
             bbox=dict(boxstyle="round,pad=0.3", fc="yellow", ec="b", lw=1, alpha=0.7))


plt.title('2D PCA Visualization of Feature Space, Clusters, and Uploaded Image')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.grid(True, linestyle='--', alpha=0.5)
# Create a legend for the clusters using cleaned labels
legend_elements = [plt.Line2D([0], [0], marker='o', color='w',
                              label=label.replace('_', ' ').replace('Cluster ', ''),
                              markerfacecolor=plt.cm.viridis(i/len(discovered_labels)), markersize=10)
                   for i, label in enumerate(discovered_labels)]
plt.legend(handles=legend_elements, title="Clusters")

plt.show()

print("\n--- VISUALIZATION EXPLANATION ---")
print("This plot shows the high-dimensional VGG16 features reduced to 2D using PCA.")
print("Each point represents an image, colored by its assigned K-Means cluster.")
print("The 'X' marks are the cluster centroids.")
print(f"The large cyan asterisk marks your uploaded image, classified as '{category_label}' with {confidence*100:.1f}% confidence.")
print(f"The dashed line connects your image to its assigned cluster centroid ('{discovered_labels[cluster_id].split('_')[-1]}').")
print("The confidence is derived from how close the uploaded image's feature vector is to the center of its assigned cluster, relative to other clusters. Closer to the centroid generally means higher confidence.")

"""## Resources"""

num_images_used = MAX_SAMPLES

plt.figure(figsize=(6, 4))
plt.bar(['Images Used'], [num_images_used], color='skyblue')
plt.ylabel('Number of Images')
plt.title('Number of Images Used for Model Training')
plt.text(0, num_images_used + 0.5, str(num_images_used), ha='center', va='bottom')
plt.ylim(0, num_images_used * 1.2)
plt.show()

print(f"Total images from the train folder used for training: {num_images_used}")